// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-west-2",
    "aws_content_delivery_bucket": "reacts3imagedemo-20181117080735--hostingbucket",
    "aws_content_delivery_bucket_region": "us-west-2",
    "aws_content_delivery_url": "http://reacts3imagedemo-20181117080735--hostingbucket.s3-website-us-west-2.amazonaws.com",
    "aws_cognito_identity_pool_id": "us-west-2:5b00e23c-5ab6-4818-9e5f-5f691630f87b",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_Ns1vcUWUd",
    "aws_user_pools_web_client_id": "6hiubhkqmpis1vf984oum9lhs1",
    "aws_user_files_s3_bucket": "reacts3imagedemo6c18f23d90874531ad1da79d61252afd",
    "aws_user_files_s3_bucket_region": "us-west-2"
};


export default awsmobile;
